version: "3.9"
   
services:
  backend:
    build: .
    tty: true
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - elasticsearch
    environment:
      REDIS_URL: "redis://redis:6379/0"
      ELASTIC_URL: "http://elasticsearch:9200/"
  redis:
    image: "redis:alpine"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
    environment:
      http.host: 0.0.0.0
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms500m -Xmx500m"
