version: "3.9"
   
services:
  backend:
    build: .
    tty: true
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - elasticsearch
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
    ports:
      - "9200:9200"
    environment:
      http.host: 0.0.0.0
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms500m -Xmx500m"
