version: "3.9"
   
services:
  redis:
    image: "redis:alpine"
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - 6379:6379
    volumes:
      - "./data/redis:/data"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
    ports:
      - 9200:9200
    volumes:
      - "./data/elastic:/usr/share/elasticsearch/data"
    environment:
      http.host: 0.0.0.0
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms500m -Xmx500m"
      TAKE_FILE_OWNERSHIP: 1
