# adapted from https://github.com/svenstaro/miniserve/blob/master/.github/workflows/publish.yml

name: Publish release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: ${{ matrix.os }} for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
        include:
          - os: ubuntu-18.04
            target: x86_64-unknown-linux-gnu
            artifact_name: target/x86_64-unknown-linux-gnu/release/oas
            release_name: x86_64-unknown-linux-gnu
            cross: true
            strip: true
            compress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --locked --target=${{ matrix.target }}
          use-cross: ${{ matrix.cross }}

      - name: Compress binaries
        uses: svenstaro/upx-action@v2
        with:
          file: ${{ matrix.artifact_name }}
          args: --lzma
          strip: ${{ matrix.strip }}
        if: ${{ matrix.compress }}

      - name: Get tag name
        id: tag_name
        run: |
          echo ::set-output name=current_version::${GITHUB_REF#refs/tags/v}
        shell: bash

      - name: Get CHANGELOG.md entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v1
        with:
          version: ${{ steps.tag_name.outputs.current_version }}
          path: ./CHANGELOG.md

      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.artifact_name }}
          tag: ${{ github.ref }}
          asset_name: oas-$tag-${{ matrix.release_name }}
          body: ${{ steps.changelog_reader.outputs.log_entry }}
